### ISSUE TITLE
camera error

### ISSUE THREAD

**Issue by revelonetime** [abbasabidi85/hackintosh-Dell-Vostro-3568-macOS-EFI-OpenCore#1]
there is no connected camera![image](https://github.com/abbasabidi85/hackintosh-Dell-Vostro-3568-macOS-EFI-OpenCore/assets/49829500/c0a87a3b-8846-41fd-9b47-acef9a8864df)

**Comment by revelonetime** [comment]
![image](https://github.com/abbasabidi85/hackintosh-Dell-Vostro-3568-macOS-EFI-OpenCore/assets/49829500/06de5e3e-6bcc-4754-880d-7d6905fbb50c)

**Comment by abbasabidii** [comment]
This error is because of `USBMap.Kext` being wonky, it's fixed in latest release.

Try latest release v1.4.1
Make sure you use `MacBookPro14,1` SMBIOS

If you still face this issue [map your USB ports.](https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html)

And boot issue was because of `SecureBootModel` being set to `x86legacy`. For Installation set it to `Disabled` and post installation set it back to `x86legacy`.

Also latest release has fix for brightness keys **Fn11 & Fn12** and better performance and battery backup because of change in Apple ALC layout id 11, layout id 13 was causing Kernel_task taking very high CPU usage.

**Comment by revelonetime** [comment]
Thank you i am outside from home 
I will check this when I back to my home 🙏

**Comment by abbasabidii** [comment]
> Thank you i am outside from home I will check this when I back to my home 🙏

Sure and feel free to ask anything else.

Btw I can see you have used default platform info which is iMac, for optimal performance generate platform info based upon `MacBookPro14,1` SMBIOS, follow [this](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios) guide.
